#!/bin/sh
	update-alternatives --remove  passwd /usr/bin/passwd.shadow
	update-alternatives --remove  chfn /usr/bin/chfn.shadow
	update-alternatives --remove  newgrp /usr/bin/newgrp.shadow
	update-alternatives --remove  chsh /usr/bin/chsh.shadow
	update-alternatives --remove  groups /usr/bin/groups.shadow
	update-alternatives --remove  chpasswd /usr/sbin/chpasswd.shadow
	update-alternatives --remove  login /bin/login.shadow
	update-alternatives --remove  vipw /sbin/vipw.shadow
	update-alternatives --remove  vigr /sbin/vigr.shadow
